### ISSUE TITLE
error in v1.1.1 when region is NoneType

### ISSUE THREAD

**Issue by charlyngee** [seporaitis/yum-s3-iam#53]
I'm getting the following error when trying to run yum w/ this plugin v1.1.1
v1.1.0 is still working fine.

  ```
File "/usr/lib/yum-plugins/s3iam.py", line 116, in prereposetup_hook
    replace_repo(repos, repo)
  File "/usr/lib/yum-plugins/s3iam.py", line 100, in replace_repo
    repos.add(S3Repository(repo.id, repo))
  File "/usr/lib/yum-plugins/s3iam.py", line 136, in __init__
    if 'cn-north-1' in region:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by holybit** [comment]
Total show stopper for us as we are not pinned to `v1.1.0`. Either this gets fixed ASAP as we have a bunch of Jenkins builds failing on build or we pin.

```
...
Step 9 : RUN curl -sS "https://raw.githubusercontent.com/seporaitis/yum-s3-iam/master/s3iam.py" -o /usr/lib/yum-plugins/s3iam.py -f &&   curl -sS "https://raw.githubusercontent.com/seporaitis/yum-s3-iam/master/s3iam.conf" -o /etc/yum/pluginconf.d/s3iam.conf -f &&   chmod +x /usr/lib/yum-plugins/s3iam.py
 ---> Using cache
 ---> 0e510b29009a
...
...
...
Step 12 : RUN yum install -y   nagios-client-rp   yum clean all
 ---> Running in 91989dc44cf4
Loaded plugins: fastestmirror, ovl, s3iam
Traceback (most recent call last):
  File "/usr/bin/yum", line 29, in <module>
    yummain.user_main(sys.argv[1:], exit_code=True)
  File "/usr/share/yum-cli/yummain.py", line 370, in user_main
    errcode = main(args)
  File "/usr/share/yum-cli/yummain.py", line 179, in main
    result, resultmsgs = base.doCommands()
  File "/usr/share/yum-cli/cli.py", line 573, in doCommands
    return self.yum_cli_commands[self.basecmd].doCommand(self, self.basecmd, self.extcmds)
  File "/usr/share/yum-cli/yumcommands.py", line 445, in doCommand
    return base.installPkgs(extcmds, basecmd=basecmd)
  File "/usr/share/yum-cli/cli.py", line 973, in installPkgs
    txmbrs = self.install(pattern=arg)
  File "/usr/lib/python2.7/site-packages/yum/__init__.py", line 4819, in install
    mypkgs = self.pkgSack.returnPackages(patterns=pats,
  File "/usr/lib/python2.7/site-packages/yum/__init__.py", line 1074, in <lambda>
    pkgSack = property(fget=lambda self: self._getSacks(),
  File "/usr/lib/python2.7/site-packages/yum/__init__.py", line 778, in _getSacks
    self.repos.populateSack(which=repos)
  File "/usr/lib/python2.7/site-packages/yum/repos.py", line 347, in populateSack
    self.doSetup()
  File "/usr/lib/python2.7/site-packages/yum/repos.py", line 122, in doSetup
    self.ayum.plugins.run('prereposetup')
  File "/usr/lib/python2.7/site-packages/yum/plugins.py", line 188, in run
    func(conduitcls(self, self.base, conf, **kwargs))
  File "/usr/lib/yum-plugins/s3iam.py", line 116, in prereposetup_hook
    replace_repo(repos, repo)
  File "/usr/lib/yum-plugins/s3iam.py", line 100, in replace_repo
    repos.add(S3Repository(repo.id, repo))
  File "/usr/lib/yum-plugins/s3iam.py", line 136, in __init__
    if 'cn-north-1' in region:
TypeError: argument of type 'NoneType' is not iterable
The command '/bin/sh -c yum install -y   nagios-client-rp   yum clean all' returned a non-zero code: 1
make: *** [Makefile:117: build-worker-event-prod] Error 1
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

**Comment by mbrossard** [comment]
Working on a fix

**Comment by mbrossard** [comment]
Can you confirm this fixes the issue?

**Comment by holybit** [comment]
I'll check first thing tomorrow MST - 8 am. Thanks for looking at it so quickly.

**Comment by holybit** [comment]
@mbrossard I have confirmed the fix works. Tested against two of our failing Jenkins builds and both went through the s3iam.py build steps with out issue.

**Comment by charlyngee** [comment]
@mbrossard I can also confirm your fix works. Thank you for taking care of it!

**Comment by mbrossard** [comment]
@charlyngee, @holybit Thanks for your help, I'll close this issue and tag this release.
